defaults: &defaults
  rollbar_token: fake-token
  company: netguru
  permissions_repo:
    url: http://url-to-repo-with-permissions
    git: git@address.to.repo.with.permissions
    checkout_dir: 'tmp/permissions'
  secret_key_base: "i-m-so-overriden-in-the-sec-config"
  github:
    client_id: a
    client_secret: b


test:
  <<: *defaults
  permissions_repo:
    checkout_dir: 'spec/get_diff_yamls'

development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
  github:
    client_id: <%= ENV["GH_CLIENT_ID"] %>
    client_secret: <%= ENV["GH_CLIENT_SECRET"] %>
