defaults: &defaults
  rollbar_token: fake-token
  company: netguru
  cache_data: true
  permissions_repo:
    url: http://url-to-repo-with-permissions
    git: git@address.to.repo.with.permissions
    checkout_dir: 'tmp/permissions'
  secret_key_base: "i-m-so-overriden-in-the-sec-config"
  github:
    client_id: a
    client_secret: b
  google:
    domain_member_id: 'This little guy is in sec-config.'
    main_domain: netguru.pl
    other_domains:
      - netguru.co
      - netguru.pl
    scope: 
      - 'email'
      - 'profile'
      - 'https://www.googleapis.com/auth/plus.me'
      - 'https://www.googleapis.com/auth/admin.directory.user'
      - 'https://www.googleapis.com/auth/admin.directory.group'
      - 'https://www.googleapis.com/auth/admin.directory.user.security'
    client_id: 'I couldnt possibly be any more in sec_config, than I am now. Just sayin'
    client_secret: 'Same here, bro. Totally and utterly in sec_config. Chillin'
    config_json: 'config/client_secrets.json'
  features:
    google_integration: false

test:
  <<: *defaults
  permissions_repo:
    checkout_dir: 'spec/get_diff_yamls'

development:
  <<: *defaults
  features:
    google_integration: true
  cache_data: true

staging:
  <<: *defaults

production:
  <<: *defaults
  github:
    client_id: <%= ENV["GH_CLIENT_ID"] %>
    client_secret: <%= ENV["GH_CLIENT_SECRET"] %>
  google:
    client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
    client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
    scope: <%= ENV["GOOGLE_SCOPE"] %>
  slack:
    webhook_url: <%= ENV["SLACK_WEBHOOK_URL"] %>
    default_channel: <%= ENV["SLACK_DEFAULT_CHANNEL"] %>
